[book]
authors = ["../AUTHORS.md"]
language = "en"
multilingual = false
src = "src"
title = "Crisp Documentation"

[output.html]
git-repository-url = "https://github.com/ChristopherBilg/crisp"
edit-url-template = "https://github.com/ChristopherBilg/crisp/edit/master/docs/{path}"
site-url = "/crisp/"
cname = "chrisbilger.com/crisp/"
